-- Openreach billing parser schema bootstrap
-- Usage:
--   psql "$BILLING_DB_DSN" -f db/schema.sql

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE SCHEMA IF NOT EXISTS openreach;

CREATE TABLE IF NOT EXISTS openreach.billing_invoices (
    invoice_id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    customer_reference varchar(20),
    account_reference varchar(20),
    invoice_reference varchar(20),
    bill_tax_date date,
    bill_type varchar(20) CHECK (
        bill_type IN (
            'Periodic',
            'Interim',
            'Initiation',
            'Termination',
            'VAT Credit',
            'Budget Center Report',
            'Post Termination',
            'Suspension'
        )
    ),
    bill_title varchar(80),
    net_total numeric(10,2),
    total_vat numeric(10,2),
    non_vat_total numeric(10,2),
    invoice_total numeric(10,2),
    one_off_charges numeric(10,2),
    periodic_charges numeric(10,2),
    event_charges numeric(10,2),
    non_product_event_charges numeric(10,2),
    total_usage_charges numeric(10,2),
    total_adjustments numeric(10,2)
);

CREATE TABLE IF NOT EXISTS openreach.billing_product_charges (
    product_charge_id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    invoice_id uuid REFERENCES openreach.billing_invoices(invoice_id),
    product_description varchar,
    tariff_name varchar,
    product_label varchar(80),
    charge_description varchar,
    start_date date,
    end_date date,
    address_line_1 varchar(80),
    postcode varchar(16),
    or_order_number varchar(80),
    quantity smallint,
    units varchar(20),
    unit_rate numeric(10,2),
    price numeric(10,2),
    vat_status smallint,
    service_id varchar,
    price_list_reference varchar(256),
    price_list_description varchar(256),
    unique_price_code varchar(60)
);

CREATE TABLE IF NOT EXISTS openreach.billing_event_charges (
    event_id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    invoice_id uuid REFERENCES openreach.billing_invoices(invoice_id),
    event_source varchar(40),
    event_description varchar(80),
    charge_reason varchar(40),
    event_date date,
    end_date date,
    address_line_1 varchar(80),
    postcode varchar(16),
    or_order_number varchar(80),
    quantity smallint,
    event_cost numeric(10,2),
    vat_status smallint,
    service_id varchar(40),
    price_list_reference varchar(256),
    price_list_description varchar(256),
    product_set varchar(40),
    unique_price_code varchar(60)
);

CREATE TABLE IF NOT EXISTS openreach.billing_adjustments (
    adjustment_id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    invoice_id uuid REFERENCES openreach.billing_invoices(invoice_id),
    adjustment_name varchar(40),
    product_tariff_name varchar(40),
    adjustment_free_text_field varchar(255),
    charge_description_type varchar(20),
    charge_reason varchar(40),
    adjustment_date date,
    end_date date,
    address_line_1 varchar(80),
    postcode varchar(16),
    css_seibel_job_number varchar(20),
    sp_order_fault_number_1 varchar(20),
    sp_order_fault_number_2 varchar(20),
    quantity smallint,
    units varchar(40),
    unit_rate numeric(10,2),
    net_value numeric(10,2),
    vat_status smallint,
    css_account_number varchar(20),
    product_type varchar(20),
    or_service_id varchar(20),
    circuit_id varchar(20),
    mdf_site varchar(20),
    room_id varchar(20),
    service_id varchar(40),
    event_class varchar(20),
    event_name varchar(20),
    cbuk_reference_number varchar(20),
    cli varchar(20),
    mac_code varchar(20),
    trc_start_date_time timestamp,
    clear_code varchar(20),
    trc_description_code varchar(20),
    price_list_reference varchar(256),
    price_list_description varchar(256)
);

CREATE TABLE IF NOT EXISTS openreach.billing_rcs_adjustments (
    rcs_adjustment_id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    invoice_id uuid REFERENCES openreach.billing_invoices(invoice_id),
    adjustment_name varchar(40),
    product_tariff_name varchar(40),
    adjustment_free_text_field varchar(255),
    charge_description_type varchar(20),
    charge_reason varchar(40),
    adjustment_date date,
    end_date date,
    address_line_1 varchar(80),
    postcode varchar(16),
    css_seibel_job_number varchar(20),
    sp_order_fault_number_1 varchar(20),
    sp_order_fault_number_2 varchar(20),
    quantity smallint,
    units varchar(40),
    unit_rate numeric(10,2),
    net_value numeric(10,2),
    vat_status smallint,
    css_account_number varchar(20),
    product_type varchar(20),
    or_service_id varchar(20),
    circuit_id varchar(20),
    mdf_site varchar(20),
    room_id varchar(20),
    service_id varchar(40),
    event_class varchar(20),
    event_name varchar(20),
    cbuk_reference_number varchar(20),
    cli varchar(20),
    mac_code varchar(20),
    trc_start_date_time timestamp,
    clear_code varchar(20),
    trc_description_code varchar(20),
    price_list_reference varchar(256),
    price_list_description varchar(256)
);

CREATE TABLE IF NOT EXISTS openreach.billing_circuit_summary (
    circuit_summary_id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    invoice_id uuid REFERENCES openreach.billing_invoices(invoice_id),
    circuit_number varchar(20),
    a_end_1141_code varchar(20),
    b_end_1141_code varchar(20),
    customer_order_number varchar(20),
    distance bigint,
    provide_order_date date,
    cease_date date,
    connection_charge numeric(10,2),
    bpr_days smallint,
    bpr_rental smallint,
    rental_charge numeric(10,2),
    credit_rental numeric(10,2),
    total_rental numeric(10,2),
    other_charges numeric(10,2),
    total_circuit_charges numeric(10,2)
);
